### ISSUE TITLE
Unable to Read - White font on yellow background in Error messages

### ISSUE THREAD

**Issue by rdeprera** [mozilla/releases-comm-central#46]
When receiving an error in the process of **creating email accounts (popup dialog)**, they appear in **white font over a light yellow background**, making it **impossible to read**. When trying to change the theme to suppress the issue, none of the themes change the background or font color of the error messages that appear in the account creation popup. **Tested with themes**: Standard, Dark and Light.

_Thanks for attention._

**Comment by rdeprera** [comment]
I'm using Thunderbird v78.14.0 (64-bit) on GNU/Linux (Debian Bullseye)

**Comment by Rexogamer** [comment]
You'll probably want to report this on [Bugzilla](http://bugzilla.mozilla.org/).

**Comment by rdeprera** [comment]
[Bug reported on Bugzilla] (
https://bugzilla.mozilla.org/show_bug.cgi?id=1756084 as suggested) as
suggested
*Thanks*!

Em qui., 17 de fev. de 2022 às 20:48, Ed L ***@***.***>
escreveu:
